[profile.default]
solc = "0.8.17"
src = "contracts"
out = "out"
libs = ["lib", "contracts/permit2"]

remappings = [
    "forge-std/=contracts/permit2/lib/forge-std/src/",
    "solmate/=contracts/permit2/lib/solmate/",
    "ds-test/=contracts/permit2/lib/ds-test/src/",
    "openzeppelin-contracts/=contracts/permit2/lib/openzeppelin-contracts/contracts"
]